import "./globals.css";
import localFont from "next/font/local";

const berkeley = localFont({
  src: [
    {
      path: "../public/fonts/BerkeleyMonoRegular.woff2",
      weight: "100",
    },
  ],
  variable: "--font-berkeley",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${berkeley.variable}`}>
      <body>{children}</body>
    </html>
  );
}
